### ISSUE TITLE
Compile error: MedisanaBS444' has no member named 'parent'

### ISSUE THREAD

**Issue by JvD12** [bwynants/weegschaal#4]
I'm not able to compile the code: 

![image](https://github.com/bwynants/weegschaal/assets/74301365/1796c577-424c-4947-ada4-1bf6ee3db9fe)

How can I fix this? I tried to compile the code for a m5stack-atom

**Comment by bwynants** [comment]
try to compile an example from https://esphome.io/components/sensor/ble_client.html does that work?

**Comment by JvD12** [comment]
The ble example works without (compile) issues. 

I added these lines into the yaml file: 
```
external_components:
  - source: 
      type: local
      path: components

medisana_bs444:
    timeoffset: false # BS410 and BS444 needs timeoffset, set to false for other scales

# Example configuration entry
time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  - platform: medisana_bs444
    weight_1:
      name: "Weight User 1"
    kcal_1:
      name: "kcal User 1"
    fat_1:
      name: "Fat User 1"
    tbw_1:
      name: "Water User 1"
    muscle_1:
      name: "Muscle User 1"
    bone_1:
      name: "Bone User 1"
    bmi_1:
      name: "BMI User 1"

    weight_2:
      name: "Weight User 2"
    kcal_2:
      name: "kcal User 2"
    fat_2:
      name: "Fat User 2"
    tbw_2:
      name: "Water User 2"
    muscle_2:
      name: "Muscle User 2"
    bone_2:
      name: "Bone User 2"
    bmi_2:
      name: "BMI User 2"
```
Below the build log with also a reference to the ESPHome version: 
```
INFO ESPHome 2023.10.3
INFO Reading configuration /config/esphome/pico-2.yaml...
INFO Detected timezone 'Europe/Amsterdam'
INFO Generating C++ source...
INFO Compiling app...
Processing pico-2 (board: m5stack-atom; framework: arduino; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
Library Manager: Installing esphome/AsyncTCP-esphome @ 2.0.1
INFO Installing esphome/AsyncTCP-esphome @ 2.0.1
Unpacking  [####################################]  100%
Library Manager: AsyncTCP-esphome@2.0.1 has been installed!
INFO AsyncTCP-esphome@2.0.1 has been installed!
Library Manager: Installing esphome/ESPAsyncWebServer-esphome @ 3.1.0
INFO Installing esphome/ESPAsyncWebServer-esphome @ 3.1.0
Unpacking  [####################################]  100%
Library Manager: ESPAsyncWebServer-esphome@3.1.0 has been installed!
INFO ESPAsyncWebServer-esphome@3.1.0 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 2.0.1
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 3.1.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- ESP32 BLE Arduino @ 2.0.0
Compiling .pioenvs/pico-2/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/esp32/core.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/esp32/gpio.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/esp32/preferences.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/esp32_ble/ble.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/esp32_ble/ble_advertising.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/esp32_ble/ble_uuid.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/esp32_ble_tracker/esp32_ble_tracker.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/homeassistant/time/homeassistant_time.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/md5/md5.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/mdns/mdns_component.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/mdns/mdns_esp32.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/mdns/mdns_esp8266.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/mdns/mdns_host.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/mdns/mdns_libretiny.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/mdns/mdns_rp2040.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/medisana_bs444/Scale.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/medisana_bs444/medisanabs444.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/network/util.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/ota/ota_backend_arduino_esp32.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/ota/ota_backend_arduino_esp8266.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/ota/ota_backend_arduino_libretiny.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/ota/ota_backend_arduino_rp2040.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/ota/ota_backend_esp_idf.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/ota/ota_component.cpp.o
In file included from src/esphome/components/api/proto.h:4,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_connection.h:4,
                 from src/esphome.h:3,
                 from src/esphome/components/medisana_bs444/medisanabs444.h:5,
                 from src/esphome/components/medisana_bs444/medisanabs444.cpp:1:
src/esphome/components/medisana_bs444/medisanabs444.cpp: In member function 'virtual void esphome::medisana_bs444::MedisanaBS444::dump_config()':
src/esphome/components/medisana_bs444/medisanabs444.cpp:374:59: error: 'class esphome::medisana_bs444::MedisanaBS444' has no member named 'parent'
     ESP_LOGCONFIG(TAG, "  MAC address        : %s", this->parent()->address_str().c_str());
                                                           ^~~~~~
src/esphome/core/log.h:97:90: note: in definition of macro 'esph_log_config'
   esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)
                                                                                          ^~~~~~~~~~~
src/esphome/components/medisana_bs444/medisanabs444.cpp:374:5: note: in expansion of macro 'ESP_LOGCONFIG'
     ESP_LOGCONFIG(TAG, "  MAC address        : %s", this->parent()->address_str().c_str());
     ^~~~~~~~~~~~~
Compiling .pioenvs/pico-2/src/esphome/components/sensor/automation.cpp.o
Compiling .pioenvs/pico-2/src/esphome/components/sensor/filter.cpp.o
*** [.pioenvs/pico-2/src/esphome/components/medisana_bs444/medisanabs444.cpp.o] Error 1
```
