### ISSUE TITLE
BS430 workes with Keptenkurk but fails on ESPHome

### ISSUE THREAD

**Issue by AlexanderKas** [bwynants/weegschaal#9]
I have been using the Keptenkurk solution for quite some time but have to start it manually every time I weigh and the BT connection to the RPI was not stable. The ESPHome connects always directly after weighing, unfortunatly no data yet. 

Scale: BS430

ESPHome log:
[23:08:13][D][esp32_ble_tracker:669]: Found device DD:B8:B6:36:62:FC RSSI=-57
[23:08:13][D][esp32_ble_tracker:690]:   Address Type: RANDOM
[23:08:13][D][esp32_ble_tracker:692]:   Name: '0203B FC6236B6B8DD'
[23:08:13][D][esp32_ble_tracker:219]: Pausing scan to make connection...
[23:08:13][D][esp32_ble_tracker:219]: Pausing scan to make connection...
[23:08:13][I][esp32_ble_client:067]: [0] [DD:B8:B6:36:62:FC] 0x01 Attempting BLE connection
[23:08:13][D][esp32_ble_client:110]: [0] [DD:B8:B6:36:62:FC] ESP_GATTC_CONNECT_EVT
[23:08:13][D][esp32_ble_client:110]: [0] [DD:B8:B6:36:62:FC] ESP_GATTC_OPEN_EVT
[23:08:13][D][MedisanaBS444:108]: ESP_GATTC_OPEN_EVT!
[23:08:13][I][MedisanaBS444:111]: Connected successfully!
[23:08:13][D][esp32_ble_tracker:270]: Starting scan...
[23:08:14][D][esp32_ble_client:306]: [0] [DD:B8:B6:36:62:FC] Event 46
[23:08:14][D][esp32_ble_client:110]: [0] [DD:B8:B6:36:62:FC] ESP_GATTC_SEARCH_CMPL_EVT
[23:08:14][I][esp32_ble_client:227]: [0] [DD:B8:B6:36:62:FC] Connected
[23:08:14][D][MedisanaBS444:158]: ESP_GATTC_SEARCH_CMPL_EVT!
[23:08:14][D][MedisanaBS444:186]: All characteristic found at service 000078B2-0000-1000-8000-00805F9B34FB
[23:08:14][D][esp32_ble_client:188]: [0] [DD:B8:B6:36:62:FC] cfg_mtu status 0, mtu 23
[23:08:14][D][esp32_ble_client:110]: [0] [DD:B8:B6:36:62:FC] ESP_GATTC_REG_FOR_NOTIFY_EVT
[23:08:14][D][esp32_ble_client:296]: Wrote notify descriptor 2, properties=32
[23:08:14][D][MedisanaBS444:205]: ESP_GATTC_REG_FOR_NOTIFY_EVT!
[23:08:14][D][esp32_ble_client:110]: [0] [DD:B8:B6:36:62:FC] ESP_GATTC_REG_FOR_NOTIFY_EVT
[23:08:14][D][esp32_ble_client:296]: Wrote notify descriptor 2, properties=32
[23:08:14][D][MedisanaBS444:205]: ESP_GATTC_REG_FOR_NOTIFY_EVT!
[23:08:14][D][esp32_ble_client:110]: [0] [DD:B8:B6:36:62:FC] ESP_GATTC_REG_FOR_NOTIFY_EVT
[23:08:14][D][esp32_ble_client:296]: Wrote notify descriptor 2, properties=32
[23:08:14][D][MedisanaBS444:205]: ESP_GATTC_REG_FOR_NOTIFY_EVT!
[23:08:14][D][MedisanaBS444:225]: notification on for characteristic handle 0x25
[23:08:14][D][MedisanaBS444:225]: notification on for characteristic handle 0x1b
[23:08:14][D][MedisanaBS444:225]: notification on for characteristic handle 0x1e
[23:08:14][D][MedisanaBS444:247]: request to send data sent
[23:08:14][D][ble_client:058]: All clients established, services released
[23:08:14][D][esp32_ble_client:110]: [0] [DD:B8:B6:36:62:FC] ESP_GATTC_WRITE_DESCR_EVT
[23:08:14][W][component:237]: Component esp32_ble took a long time for an operation (150 ms).
[23:08:14][W][component:238]: Components should block for at most 30 ms.
[23:08:14][D][esp32_ble_client:110]: [0] [DD:B8:B6:36:62:FC] ESP_GATTC_WRITE_DESCR_EVT
[23:08:14][D][esp32_ble_client:110]: [0] [DD:B8:B6:36:62:FC] ESP_GATTC_WRITE_DESCR_EVT
[23:08:14][D][esp32_ble_client:110]: [0] [DD:B8:B6:36:62:FC] ESP_GATTC_WRITE_DESCR_EVT
[23:08:14][D][esp32_ble_client:110]: [0] [DD:B8:B6:36:62:FC] ESP_GATTC_WRITE_DESCR_EVT
[23:08:14][D][esp32_ble_client:110]: [0] [DD:B8:B6:36:62:FC] ESP_GATTC_WRITE_DESCR_EVT
[23:08:14][D][esp32_ble_client:110]: [0] [DD:B8:B6:36:62:FC] ESP_GATTC_WRITE_DESCR_EVT
[23:08:14][D][esp32_ble_client:110]: [0] [DD:B8:B6:36:62:FC] ESP_GATTC_NOTIFY_EVT
[23:08:14][D][MedisanaBS444:254]: ESP_GATTC_NOTIFY_EVT! 0x25, 20
[23:08:14][D][MedisanaBS444:258]: data Person: 1; gender: male; age: 40; size: 1.8; activity: normal:
[23:08:14][W][component:237]: Component esp32_ble took a long time for an operation (58 ms).
[23:08:14][W][component:238]: Components should block for at most 30 ms.
[23:08:57][D][esp32_ble_client:172]: [0] [DD:B8:B6:36:62:FC] ESP_GATTC_DISCONNECT_EVT, reason 19
[23:08:57][D][MedisanaBS444:118]: ESP_GATTC_DISCONNECT_EVT!
[23:08:57][I][MedisanaBS444:123]: Person Person: 1; gender: male; age: 40; size: 1.8; activity: normal:
[23:08:57][D][esp32_ble_client:110]: [0] [DD:B8:B6:36:62:FC] ESP_GATTC_CLOSE_EVT

Anyone any idea?

**Comment by fragonib** [comment]
➕1 Same here

**Comment by bwynants** [comment]
you are on the right github branch? there are 2 brances...

**Comment by fragonib** [comment]
Yeah, In fact I tested with both branches/conf. Let me gather the output log for both...

**Comment by fragonib** [comment]
This is the log and the conf I used in the first test:

Scale: BS440

```
[18:40:06]configsip: 0, SPIWP:0xee
[18:40:06]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[18:40:06]mode:DIO, clock div:2
[18:40:06]load:0x3fff0030,len:1184
[18:40:06]load:0x40078000,len:13132
[18:40:06]load:0x40080400,len:3036
[18:40:06]entry 0x400805e4
[18:40:06][I][logger:156]: Log initialized
[18:40:06][E][MedisanaBS444:048]: MedisanaBS444 constructed
[18:40:06][I][MedisanaBS444:079]: setting time 0!
[18:40:06][I][app:029]: Running through setup()...
[18:40:06][W][component:157]: Component wifi set Warning flag: scanning for networks
[18:40:09][I][wifi:541]: - 'ERWIFI' [redacted]▂▄▆█
[18:40:09][I][wifi:313]: WiFi Connecting to 'ERWIFI'...
[18:40:10][W][esp32_ble_tracker:114]: Too many BLE events to process. Some devices may not show up.
[18:40:10][I][wifi:617]: WiFi Connected!
[18:40:10][I][app:062]: setup() finished successfully!
[18:40:10][W][component:170]: Component wifi cleared Warning flag
[18:40:10][W][component:157]: Component api set Warning flag: unspecified
[18:40:10][I][app:100]: ESPHome version 2024.8.1 compiled on Sep 10 2024, 20:56:19
[18:40:10][I][app:102]: Project bwynants.weegschaal version 0.9.0
[18:40:11][W][component:170]: Component api cleared Warning flag
[18:40:32][I][esp32_ble_client:067]: [0] [F4:D1:B6:87:DB:B9] 0x01 Attempting BLE connection
[18:40:32][I][MedisanaBS444:111]: Connected successfully!
[18:40:33][I][esp32_ble_client:227]: [0] [F4:D1:B6:87:DB:B9] Connected
[18:41:06][I][safe_mode:041]: Boot seems successful; resetting boot loop counter
[18:41:17][I][MedisanaBS444:123]: Person Person: 1; gender: male; age: 38; size: 1.68; activity: normal:
```

Conf:
```
substitutions:
  device_name: "weegschaal"
  user_0: Fran
  user_1: Alicia

external_components:
  - source:
      type: git
      url: https://github.com/bwynants/weegschaal
      ref: main
    components: [ medisana_bs444 ]

esphome:
  name: ${device_name}
  friendly_name: Weegschaal
  project:
    name: bwynants.$device_name
    version: "0.9.0"

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name} Fallback Hotspot
    ap_timeout: 15s

#captive_portal:
    
#web_server:
#  port: 80

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: false

ble_client:
  - mac_address: "F4:D1:B6:87:DB:B9"
    id: medisanabs44_ble_id

sensor:
  - platform: medisana_bs444
    ble_client_id: medisanabs44_ble_id
    timeoffset: true # BS410 and BS444 needs timeoffset, set to false for other scales
    weight_1:
      name: Weight ${user_0}
    kcal_1:
      name: kcal ${user_0}
    fat_1:
      name: Fat ${user_0}
    tbw_1:
      name: Water ${user_0}
    muscle_1:
      name: Muscle ${user_0}
    bone_1:
      name: Bone ${user_0}
    bmi_1:
      name: BMI ${user_0}

    weight_2:
      name: Weight ${user_1}
    kcal_2:
      name: kcal ${user_1}
    fat_2:
      name: Fat ${user_1}
    tbw_2:
      name: Water ${user_1}
    muscle_2:
      name: Muscle ${user_1}
    bone_2:
      name: Bone ${user_1}
    bmi_2:
      name: BMI ${user_1}

  - platform: uptime
    id: uptime_sensor
    entity_category: diagnostic
    update_interval: 60s
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
                 int seconds = round(id(uptime_sensor).raw_state);
                 int days = seconds / (24 * 3600);
                 seconds = seconds % (24 * 3600);
                 int hours = seconds / 3600;
                 seconds = seconds % 3600;
                 int minutes = seconds /  60;
                 seconds = seconds % 60;
                 return (
                   (days ? to_string(days) + "d " : "") +
                   (hours ? to_string(hours) + "h " : "") +
                   (minutes ? to_string(minutes) + "m " : "") +
                   (to_string(seconds) + "s")
                 ).c_str();

  - platform: template
    name: "Free Memory"
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: 'kB'
    state_class: measurement

  - platform: wifi_signal
    name: Wi-Fi Signal
    update_interval: 60s
    entity_category: diagnostic


button:
  - platform: restart
    entity_category: diagnostic
    name: Restart

text_sensor:
  - platform: template
    name: Uptime
    id: uptime_human
    icon: mdi:clock-start
    entity_category: diagnostic

  - platform: wifi_info
    ip_address:
      name: IP Address
      disabled_by_default: true
      entity_category: diagnostic

time:
  - platform: homeassistant
    id: homeassistant_time
    timezone: Europe/Madrid
```
